version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
#  front-tier: ---> Grafana is disabled
  back-tier:

services:

  prometheus:
    image: prom/prometheus:v2.28.1
    volumes:
      - /prometheus/data:/prometheus/
      - /prometheus/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
#      - alertmanager:alertmanager
#      - pushgateway:pushgateway
    depends_on:
      - cadvisor
#      - pushgateway
    networks:
      - back-tier
    restart: always
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}
  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    networks:
      - back-tier
    dns: 8.8.8.8
    restart: always
    volumes:
      - '/prometheus/config:/config'
    command: --config.file=/config/blackbox.yaml

  # alertmanager:
  #   image: prom/alertmanager
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - ./alertmanager/:/etc/alertmanager/
  #   networks:
  #     - back-tier
  #   restart: always
  #   command:
  #     - '--config.file=/etc/alertmanager/config.yaml'
  #     - '--storage.path=/alertmanager'
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8880:8080
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

