modules:
  http_2xx:
    prober: http
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  icmp_ipv4:
    prober: icmp
    icmp:
      preferred_ip_protocol: ip4