# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'ayroor'


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']


  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://grafana.vbin.in    # Target to probe with http.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.

  - job_name: node
    static_configs:
    - targets: ['192.168.4.5:9100']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:  ['192.168.4.5:8880']


  - job_name: 'blackbox_icmp'
    metrics_path: /probe
    params:
      module: [icmp_ipv4]  
    static_configs:
      - targets:
        - localhost
        - 192.168.68.1
        # Ayroor Mesh 1st Floor
        - 192.168.68.103
        # Ayroor Mesh Kitchen
        - 192.168.68.105
        # Ayroor iRobot
        - 192.168.68.104
        - 192.168.68.101
        # Ayroor Amma phone
        - 192.168.68.107
        # Ayroor NUC
        - 192.168.68.100
        # Ayroor Sidecamera Facing old toilet
        - 192.168.68.108
        # Ayroor Sidecamera Facing kitchen
        - 192.168.68.109
        # Ayroor Backcamera Facing river
        - 192.168.68.101
        # Ayroor Front camera
        - 192.168.68.102
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # This is your blackbox exporter.